### ISSUE TITLE
Verse identifiers with CoNLL-U

### ISSUE THREAD

**Issue by robertostling** [proiel/proiel-cli#4]
This could be either a feature request or a question: what is the simplest way to include verse numbers (the value of the `citation-part` attribute from the New Testament XML files) in the CoNLL-U output, for instance as an additional column?

The goal is to use Universal Dependencies-compatible annotations with a corpus of unannotated translations, feel free to suggest other means towards this goal.

Although it's been a long time since I used Ruby, if necessary I could probably get this done myself with some help (such as fixing the syntax error I just submitted as a separate issue).

**Comment by daghaug** [comment]
I agree this is desirable. An additional column would break the CoNLL-U 
format specification. But CoNLL-U (unlike CoNLL-X) allows comment lines 
starting with #, so one option would be to add comment lines with the 
citation-part at the beginning of each sentence + at each point inside 
the sentence where the citation-part changes. Alternatively, if CoNLL-U 
allowed inline comments, we could add each token's citation-part as a 
comment at the end of each line, but I'm not sure they want that.

I agree we should have this, so I'll file a question in the 
universal-dependencies repo to see if there is any interest in 
developing a standard for this. If not, I guess we should go ahead with 
comment lines.

**Comment by robertostling** [comment]
Another option that would not break the standard would be to use the MISC column of CoNLL-U, which is available for "any other annotation", this would avoid having to hide contents in comments. Might have to be careful about other uses of this column, but as far as I know the UD treebanks don't use it.

**Comment by robertostling** [comment]
I've modified the CoNLL-U conversion code to include verse identifiers in the MISC field. This is sufficient for our needs, so I'm satisfied now. If you want the patch I could send a pull request, but if you prefer to implement the comment solution Dag mentioned that's fine with me of course.

**Comment by daghaug** [comment]
OK. I mentioned this possibility in my question in the UD list, so if 
that's an acceptable solution for them, I'll let you know and we could 
include this.

**Comment by daghaug** [comment]
The view of the UD community seems to be that this should go in the MISC 
field, so could you send a pull request?

As Dan Zeman pointed out in the discussion, whitespace is not allowed in 
UD fields, so we should have something like this:

ref=LUKE_7.17

Dag

**Comment by mlj** [comment]
@daghaug, can you add a link to the discussion for future reference? (If it's on github there's a shortcut, see https://guides.github.com/features/issues/.)

**Comment by daghaug** [comment]
The discussion is here: UniversalDependencies/docs#240
